apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver 
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: jmalloc/echo-server
        imagePullPolicy: IfNotPresent