apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod2
  namespace: apps
spec:
  serviceAccountName: flux-sa-dev-team
  releaseName: pod2
  chart:
    spec:
      chart: pod2
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 5m
