apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
#  - .././base
patchesStrategicMerge:
  - ./apps/podinfo/podinfo-values.yaml
  - ./apps/pod2/pod2-values.yaml
  - ./apps/mysql/manifest.yaml